name: Scaffoldly Deploy

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 12 * * *"

permissions:
  id-token: write
  contents: read

env:
  # AWS_REGION: us-east-1 # Optional, defaults to us-east-1
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
  SLY_DEBUG: true

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          brew install --cask docker

      - name: Start Docker service
        run: open /Applications/Docker.app

      - name: Wait for Docker to start
        run: |
          while ! docker info > /dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 1
          done

      - name: Deploy
        uses: scaffoldly/scaffoldly@v1
        with:
          secrets: ${{ toJSON(secrets) }}
