name: Submodules Maintenance

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 6 * * *"

permissions:
  id-token: write
  contents: write

jobs:
  sync-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules to their latest version
        run: |
          git submodule update --remote --recursive
          git add .
          git commit -m "Daily update of submodules" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
